apps/project_web/lib/project_web/router.ex
defmodule ProjectWeb.Router do
  use ProjectWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ProjectWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug ProjectWeb.Plugs.ApiAuth
  end

  if Mix.env == :dev do
   forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", ProjectWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/users/new", UserController, :new
    post "/users", UserController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout

    get "/products", ProductController, :overview
    get "/products/filter", ProductController, :filter
    get "/products/:product_id", ProductController, :show

  end

  scope "/", ProjectWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_users]

    get "/user_scope", PageController, :user_index

    get "/users", UserController, :overview
    get "/users/:user_id", UserController, :show
    get "/verify", UserController, :update_verification

    get "/cart", CartController, :show
    get "/cartOrder", OrderController, :create
    resources "/cart", CartController, only: [:update, :delete, :show]

    resources "/delivery_address", DeliveryAddressController, only: [:new, :create]

    get "/order", OrderController, :overview
    get "/order/:order_id", OrderController, :show


  end

  scope "/admin", ProjectWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_admins]

    get "/", PageController, :admin_index

    get "/users/:user_id/edit", UserController, :edit
    put "/users/:user_id", UserController, :update
    patch "/users/:user_id", UserController, :update
    get "/users/:user_id/", UserController, :delete
    delete "/users/:user_id", UserController, :delete

    #resources "/users", UserController, only: [:show] do
    resources "/api-keys", ApiKeyController, only: [:create]
    #end

    get "/products/new", ProductController, :new
    post "/products", ProductController, :create
    post "/productsBulk", ProductController, :createBulk

    get "/products/:product_id/edit", ProductController, :edit
    put "/products/:product_id", ProductController, :update
    patch "/products/:product_id", ProductController, :update
    get "/products/:product_id/", ProductController, :delete
    delete "/products/:product_id", ProductController, :delete

  end

  scope "/api", ProjectWeb.Api, as: :api do
    pipe_through :api
    resources "/products", ProductController, only: [:show, :index]

    pipe_through :api_auth
    resources "/users", UserController, only: [:show, :index]

  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ProjectWeb.Telemetry
    end
  end

  pipeline :auth do
    plug ProjectWeb.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :allowed_for_users do
    plug ProjectWeb.Plugs.AuthorizationPlug, ["Admin", "User"]
  end

  pipeline :allowed_for_admins do
    plug ProjectWeb.Plugs.AuthorizationPlug, ["Admin"]
  end
end

apps/project_web/lib/project_web/views/layout_view.ex
defmodule ProjectWeb.LayoutView do
  use ProjectWeb, :view

  alias Project.Carts

  def current_user(conn) do
    current_user = Guardian.Plug.current_resource(conn)
    case current_user do
      nil ->
        nil
      current_user ->
        current_user
    end
  end

  def current_role(conn) do
    current_user = current_user(conn)
    case current_user.role do
      "User" ->
        "user"
      "Admin" ->
        "admin"
    end
  end

  def cart_item_count(conn) do
    current_user = Guardian.Plug.current_resource(conn)
    case current_user do
      nil ->
        0
      current_user ->
        case Carts.get(current_user.email) do
          nil ->
            0
          cart ->
            Enum.count(cart)
        end
    end
  end

  def new_locale(conn, locale, language_title) do
    "<a class='dropdown-item' href=\"#{Routes.user_path(conn, :new, locale: locale)}\">#{language_title}</a>" |> raw
  end
end

apps/project_web/lib/project_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Solution · Phoenix Framework</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</head>

<body>
  <header>
      <nav role="navigation" class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <ul class="navbar-nav">
            <li class="nav-item active"><%= link "Home |", to: Routes.page_path(@conn, :index), class: "nav-link" %></li>
            <%= if current_user(@conn) do%>
              <%= if current_role(@conn) == "admin" do%>
                <li class="nav-item active"><%= link "Register User |", to: Routes.user_path(@conn, :new), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Users Overview |", to: Routes.user_path(@conn, :overview), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Register Product |", to: Routes.product_path(@conn, :new), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Products Overview |", to: Routes.product_path(@conn, :overview), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Show cart |", to: Routes.cart_path(@conn, :show), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Show Orders |", to: Routes.order_path(@conn, :overview), class: "nav-link"  %></li>
                <li class="nav-link"><%= cart_item_count(@conn) %> item(s) in your cart</li>

              <% else %>
                <li class="nav-item active"><%= link "Users Overview |", to: Routes.user_path(@conn, :overview), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Products Overview |", to: Routes.product_path(@conn, :overview), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Show cart |", to: Routes.cart_path(@conn, :show), class: "nav-link"  %></li>
                <li class="nav-item active"><%= link "Show Orders |", to: Routes.order_path(@conn, :overview), class: "nav-link"  %></li>
                <li class="nav-link"><%= cart_item_count(@conn) %> item(s) in your cart</li>

              <% end %>
            <% else %>
              <li class="nav-item active"><%= link "Register User |", to: Routes.user_path(@conn, :new), class: "nav-link"  %></li>
              <li class="nav-item active"><%= link "Products Overview |", to: Routes.product_path(@conn, :overview), class: "nav-link"  %></li>
            <% end %>
            <li>
              <div>
                <%= new_locale @conn, :en, "English" %>
                <%= new_locale @conn, :nl, "Nederlands" %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
  </header>
  <main role="main" class="container">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= @inner_content %>
  </main>
</body>

</html>

apps/project_web/lib/project_web/templates/layout/email.html.eex
<html>
  <head>

  </head>
  <body>
    <div class="container">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>