apps/project_web/lib/project_web/router.ex
defmodule ProjectWeb.Router do
  use ProjectWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ProjectWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug ProjectWeb.Plugs.ApiAuth
  end

  if Mix.env == :dev do
   forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  scope "/", ProjectWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/users/new", UserController, :new
    post "/users", UserController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout

    get "/products", ProductController, :overview
    get "/products/filter", ProductController, :filter
    get "/products/:product_id", ProductController, :show

  end

  scope "/", ProjectWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_users]

    get "/user_scope", PageController, :user_index

    get "/users", UserController, :overview
    get "/users/:user_id", UserController, :show
    get "/verify", UserController, :update_verification

    get "/cart", CartController, :show
    get "/cartOrder", OrderController, :create
    resources "/cart", CartController, only: [:update, :delete, :show]

    resources "/delivery_address", DeliveryAddressController, only: [:new, :create]

    get "/order", OrderController, :overview
    get "/order/:order_id", OrderController, :show


  end

  scope "/admin", ProjectWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_admins]

    get "/", PageController, :admin_index

    get "/users/:user_id/edit", UserController, :edit
    put "/users/:user_id", UserController, :update
    patch "/users/:user_id", UserController, :update
    get "/users/:user_id/", UserController, :delete
    delete "/users/:user_id", UserController, :delete

    #resources "/users", UserController, only: [:show] do
    resources "/api-keys", ApiKeyController, only: [:create]
    #end

    get "/products/new", ProductController, :new
    post "/products", ProductController, :create
    post "/productsBulk", ProductController, :createBulk

    get "/products/:product_id/edit", ProductController, :edit
    put "/products/:product_id", ProductController, :update
    patch "/products/:product_id", ProductController, :update
    get "/products/:product_id/", ProductController, :delete
    delete "/products/:product_id", ProductController, :delete

  end

  scope "/api", ProjectWeb.Api, as: :api do
    pipe_through :api
    resources "/products", ProductController, only: [:show, :index]

    pipe_through :api_auth
    resources "/users", UserController, only: [:show, :index]

  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ProjectWeb.Telemetry
    end
  end

  pipeline :auth do
    plug ProjectWeb.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :allowed_for_users do
    plug ProjectWeb.Plugs.AuthorizationPlug, ["Admin", "User"]
  end

  pipeline :allowed_for_admins do
    plug ProjectWeb.Plugs.AuthorizationPlug, ["Admin"]
  end
end

apps/project_web/lib/project_web/controllers/api/user_controller.ex
defmodule ProjectWeb.Api.UserController do
  use ProjectWeb, :controller
  alias Project.{UserContext,OrderContext}



  def index(conn, _params) do
    users = UserContext.list_users()
    render(conn, "index.json", users: users)
  end

  def show(conn, %{"id" => id}) do
    orders = OrderContext.list_orders(id)
    render(conn, "show.json", orders: orders)
  end
end

apps/project_web/lib/project_web/controllers/user_controller.ex
defmodule ProjectWeb.UserController do
  use ProjectWeb, :controller

  alias Project.UserContext
  alias Project.UserContext.User
  alias Project.{Mailer, Email}

  #plug ProjectWeb.Plugs.CheckAuth

  def new(conn, _parameters) do
    changeset = UserContext.change_user(%User{})
    roles = UserContext.get_acceptable_roles()
    render(conn, "register.html", changeset: changeset,  acceptable_roles: roles)
  end

  defp send_registration_notification(user) do
    Email.verification_email(user) |> Mailer.deliver_later()
  end

  def create(conn, %{"user" => user_params}) do
    attrs = %{
      "verification_token" => SecureRandom.urlsafe_base64(),
      "verification_sent_at" => NaiveDateTime.utc_now()
    }

    case UserContext.create_user(Map.merge(user_params, attrs)) do
      {:ok, user} ->
        send_registration_notification(user)
        conn
        |> put_flash(:info, "User #{user.first_name} #{user.last_name} created successfully! Confirm your email.")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        roles = UserContext.get_acceptable_roles()
        render(conn, "register.html", changeset: changeset, acceptable_roles: roles)
    end
  end

  def overview(conn, _params) do
    users = UserContext.list_users()
    render(conn, "overview.html", users: users)
  end

  def show(conn, %{"user_id" => id}) do
    user = id
    |> UserContext.get_user!()
    |> UserContext.preload_api_key()
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"user_id" => id}) do
    user = UserContext.get_user!(id)
    changeset = UserContext.change_user(user)
    roles = UserContext.get_acceptable_roles()
    render(conn, "edit.html", user: user, changeset: changeset, acceptable_roles: roles)
  end

  def update(conn, %{"user_id" => id, "user" => user_params}) do
    user = UserContext.get_user!(id)
    roles = UserContext.get_acceptable_roles()
    case UserContext.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset, acceptable_roles: roles)
    end
  end

  def delete(conn, %{"user_id" => id}) do
    user = UserContext.get_user!(id)
    {:ok, _user} = UserContext.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :overview))
  end

  def update_verification(conn, %{"verification_token" => token, "user" => verification_attrs}) do
    user = UserContext.get_user_from_token(token)

    verification_attrs =
      Map.merge(verification_attrs, %{"verification_token" => nil, "verification_sent_at" => nil})

    with true <- UserContext.valid_token?(user.verification_sent_at),
         {:ok, _updated_user} <- UserContext.update_user(user, verification_attrs) do

         conn
         |> put_flash(:info, "Your account has been verified.")
         |> redirect(to: Routes.session_path(conn, :new))

    else
      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Problem verifying your account")
        |> redirect(to: Routes.session_path(conn, :new))

      false ->
        conn
        |> put_flash(:error, "Verification token expired - request new one")
        |> redirect(to: Routes.session_path(conn, :new))

    end
  end
end

apps/project_web/lib/project_web/views/user_view.ex
defmodule ProjectWeb.UserView do
  use ProjectWeb, :view

  def current_user(conn) do
    current_user = Guardian.Plug.current_resource(conn)
    case current_user do
      nil ->
        nil
      current_user ->
        current_user
    end
  end

  def current_role(conn) do
    current_user = current_user(conn)
    case current_user.role do
      "User" ->
        "user"
      "Admin" ->
        "admin"
    end
  end

  @spec current_user_key(Plug.Conn.t()) :: any
  def current_user_key(conn) do
    current_user = current_user(conn)
    case current_user.api_key do
      nil ->
        nil
      api_key ->
        api_key
    end
  end
end

apps/project_web/lib/project_web/templates/user/edit.html.eex
<h1>Edit user</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :overview) %></span>

apps/project_web/lib/project_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
<div class="alert alert-danger">
    <p><%= gettext "Oops, something went wrong! Please check the errors below."%></p>
</div>
<% end %>

<%= label f,gettext("%{first_name}", first_name: "First name") %>
<%= text_input f, :first_name %>
<%= error_tag f, :first_name %>

<%= label f, gettext("%{last_name}", last_name: "Last Name") %>
<%= text_input f, :last_name %>
<%= error_tag f, :last_name %>

<%= label f, gettext("Email") %>
<%= text_input f, :email %>
<%= error_tag f, :email %>

<%= label f, gettext("password") %>
<%= text_input f, :password %>
<%= error_tag f, :password %>

<%= label f, gettext("Country") %>
<%= text_input f, :country %>
<%= error_tag f, :country %>

<%= label f, gettext("City") %>
<%= text_input f, :city %>
<%= error_tag f, :city %>

<%= label f, gettext("Postal code") %>
<%= text_input f, :postal_code %>
<%= error_tag f, :postal_code %>

<%= label f, gettext("Street") %>
<%= text_input f, :street %>
<%= error_tag f, :street %>

<%= label f, gettext("Number") %>
<%= text_input f, :number %>
<%= error_tag f, :number %>

<%= if current_user(@conn) do %>
    <%= if current_role(@conn) == "admin" do %>
        <%= label f, gettext("Role") %>
        <%= select f, :role, @acceptable_roles %>
        <%= error_tag f, :role %>
    <% end %>
<% end %>

<div>
    <%= submit gettext("Save") %>
</div>
<% end %>

apps/project_web/lib/project_web/templates/user/overview.html.eex
<h1>Listing Users</h1>

<table>
    <thead>
        <tr>
            <th>first name</th>
            <th>last name</th>
            <th>email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <%= for user <- @users do %>
        <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <th><%= user.email %></th>

            <td>
                <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
            </td>
            <%= if current_user(@conn) do%>
                <%= if current_role(@conn) == "admin" do%>
                 <td>
                 <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
                 </td>
                 <td><span><%= link "Delete", to: Routes.user_path(@conn, :delete, user),
                    method: :delete, data: [confirm: "Are you sure?"] %></span></td>

                <% end %>
            <% end %>

        </tr>
        <% end %>
    </tbody>
</table>

<%= link "New user", to: Routes.user_path(@conn, :new) %>

apps/project_web/lib/project_web/templates/user/register.html.eex
<h1>
    <%= gettext "%{title}", title: "New user" %>
</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :overview) %></span>

apps/project_web/lib/project_web/templates/user/show.html.eex
<h1>Show User details</h1>

<ul>
    <li>
        <strong>First name:</strong>
        <%= @user.first_name %>
    </li>

    <li>
        <strong>Last name:</strong>
        <%= @user.last_name %>
    </li>

    <li>
        <strong>E-mail:</strong>
        <%= @user.email %>
    </li>
</ul>
<%= if current_role(@conn) == "admin" do %>
    <br>
    <p>Please do <b>NOT</b> generate an api-key before running the Postman scripts. This key is assigned to the Postman GET-request of api/users</p>
    <br>
    <p>Note that the request header has to be changed after creating a new key</p>
    <%= if @user.api_key do%>
        Your API key: <%= @user.api_key.key %>
    <% else %>
        Create an API-key
    <% end %>
    <%= button("Generate API-key", to: Routes.api_key_path(@conn, :create), method: "post") %>
<% end %>

<br>
<%= link "Back", to: Routes.user_path(@conn, :overview) %>